"""Capture original matrix decomposition/interpolation with synthetic affine matrices."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import random
import struct
import subprocess

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--dll', type=Path, required=True)
parser.add_argument('--runner', type=Path, required=True)
parser.add_argument('--output-dir', type=Path, required=True)
args = parser.parse_args()
dll, runner = args.dll.resolve(strict=True), args.runner.resolve(strict=True)
output = args.output_dir.resolve()
output.mkdir(parents=True, exist_ok=True)
digest = hashlib.sha256(dll.read_bytes()).hexdigest()
if digest != 'bd17dddb747c943e6e090471305aeda7f87cfbca401b3fada36be400285973a2':
    raise RuntimeError('Unexpected reference DLL')


def affine(rows, pos=(3, -5, 7)):
    return [v for row in rows for v in [*row, 0]] + [*pos, 1]


identity = affine([[1, 0, 0], [0, 1, 0], [0, 0, 1]], (0, 0, 0))
matrices = [identity]
for x, y, z in [(2, 3, 4), (-2, 3, 4), (2, 2, 5), (3, 3, 3), (0, 0, 0),
                (2, 0, 0), (0, 3, 0), (0, 0, -4), (2, 3, 0), (0, 3, -4), (2, 0, 4),
                (1e-5, 2e-5, 3e-5)]:
    matrices.append(affine([[x, 0, 0], [0, y, 0], [0, 0, z]]))
matrices += [affine([[1, .4, -.2], [0, 2, .7], [0, 0, 3]]),
             affine([[1, 2, 3], [2, 4, 6], [3, 6, 9]]),
             affine([[1, 2, 0], [0, 1, 0], [1, 3, 0]])]
rng = random.Random(0x2429B990)
for index in range(18):
    angle = rng.uniform(-2, 2)
    c, s = math.cos(angle), math.sin(angle)
    sx, sy, sz = [rng.uniform(.5, 4) for _ in range(3)]
    if index % 3 == 0: sx = -sx
    matrices.append(affine([[sx*c, -sx*s, .1*index], [sy*s, sy*c, .2], [.15, -.1, sz]],
                           [rng.uniform(-10, 10) for _ in range(3)]))
rows = []
for a in matrices:
    for op in (0, 2, 3):
        rows.append((op, 15, .375, a, identity))
for a in matrices[:7] + matrices[13:16]:
    for mask in range(16):
        rows.append((4, mask, .375, a, identity))
# Symmetric inputs exercise the spectral helper independently of polar output.
for a in matrices:
    symmetric = a[:]
    for i in range(3):
        for j in range(i+1, 3):
            symmetric[4*i+j] = symmetric[4*j+i] = .5*(a[4*i+j]+a[4*j+i])
    rows.append((1, 15, 0, symmetric, identity))
for i in [0, 1, 2, 3, 4, 5, 6, 9, 13, 16, 22, 31]:
    for step in [-.5, 0, .25, .5, 1, 1.5]:
        for op in (5, 6):
            rows.append((op, 15, step, matrices[i], matrices[(i+7) % len(matrices)]))
raw = struct.pack('<I', len(rows)) + b''.join(struct.pack('<II33f', op, mask, t, *a, *b) for op, mask, t, a, b in rows)
path = output/'decomposition-input.bin'
path.write_bytes(raw)
captures = []
runtime = []
for extra in [[], ['--scalar']]:
    result = subprocess.run([str(runner), str(dll), str(path), *extra], capture_output=True, timeout=40)
    if result.returncode or len(result.stdout) != 144*len(rows):
        raise RuntimeError((result.returncode, len(result.stdout), result.stderr))
    context = result.stderr.decode('ascii').strip()
    if context != 'x87 control word: 0x007f':
        raise RuntimeError(f'Unexpected reference FPU mode: {context}')
    runtime.append(context)
    captures.append(list(struct.iter_unpack('<36f', result.stdout)))


def f(v):
    v = struct.unpack('<f', struct.pack('<f', v))[0]
    if math.isnan(v): return 'std::numeric_limits<float>::quiet_NaN()'
    if math.isinf(v): return ('-' if v < 0 else '') + 'std::numeric_limits<float>::infinity()'
    s = format(v, '.9g')
    return s + ('.0f' if '.' not in s and 'e' not in s else 'f')


header = ['// Synthetic original DLL captures; generated by capture_decomposition.py.', '#pragma once', '#include <limits>',
          'namespace MatrixDecompositionReference {',
          'struct Sample { int operation, mask; float step, a[16], b[16], expected[36], scalar[36]; };',
          'static const Sample Samples[] = {']
for (op, mask, t, a, b), sse, scalar in zip(rows, *captures):
    arrays = ', '.join('{' + ', '.join(map(f, v)) + '}' for v in [a, b, sse, scalar])
    header.append(f'    {{{op}, {mask}, {f(t)}, {arrays}}},')
header += ['};', '}', '']
(output/'MatrixDecompositionSamples.h').write_text('\n'.join(header), encoding='utf-8')
(output/'decomposition-reference.json').write_text(json.dumps({'sha256': digest, 'count': len(rows), 'runtime': runtime, 'sse': captures[0], 'scalar': captures[1]}, indent=2), encoding='utf-8')
print(f'Captured {len(rows)} decomposition/interpolation cases in both feature modes')
