"""Generate independent sin/cos references using Decimal, not the host libm.

Run from any directory. Only synthetic numerical data is emitted.
"""
from decimal import Decimal, localcontext
from pathlib import Path
import math
import random
import re
import struct


def compute_pi():
    # Chudnovsky series, with more than 100 guard digits beyond DBL_MAX.
    m, l, x, k = 1, 13591409, 1, 6
    total = Decimal(l)
    for i in range(1, 34):
        m = m * (k * k * k - 16 * k) // (i * i * i)
        l += 545140134
        x *= -262537412640768000
        total += Decimal(m * l) / x
        k += 12
    return 426880 * Decimal(10005).sqrt() / total


def sincos(value, pi):
    angle = Decimal.from_float(value) % (2 * pi)
    if angle > pi:
        angle -= 2 * pi
    if angle < -pi:
        angle += 2 * pi
    squared = angle * angle
    sine, cosine = angle, Decimal(1)
    sine_term, cosine_term = sine, cosine
    for i in range(1, 400):
        sine_term *= -squared / ((2 * i) * (2 * i + 1))
        cosine_term *= -squared / ((2 * i - 1) * (2 * i))
        sine += sine_term
        cosine += cosine_term
        if abs(sine_term) + abs(cosine_term) < Decimal("1e-440"):
            break
    return float(sine), float(cosine)


def float32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def main():
    test_dir = Path(__file__).resolve().parents[1] / "VxMath"
    angles = {0.0, float32(1e-30), float32(.7), float32(1e10), float32(1e20),
              float.fromhex("0x1.fffffep127"), float.fromhex("0x1.fffffffffffffp1023")}
    # Include every large finite float used by the conversion fixtures so their
    # Rodrigues/Euler oracle does not depend on the Win32 CRT's argument reduction.
    for line in (test_dir / "QuaternionConversionSamples.h").read_text().splitlines():
        fields = re.match(r"\s*\{(\d+), [^{]+\{([^}]+)\}", line)
        if not fields:
            continue
        operation = int(fields[1])
        inputs = fields[2].split(", ")
        indices = (3,) if operation in (0, 7, 10) else (0, 1, 2) if operation in (1, 8) else ()
        for index in indices:
            token = inputs[index]
            if not token.endswith("f"):
                continue
            value = float32(float(token[:-1]))
            if abs(value) >= 8192:
                angles.add(value)
    rng = random.Random(20261002)
    for exponent in range(13, 1024, 7):
        value = math.ldexp(1 + rng.random(), exponent)
        angles.add(value)
        if exponent < 128:
            angles.add(float32(value))
    for exponent in (13, 31, 32, 52, 53, 63, 64, 127, 128, 255, 256, 1023):
        value = math.ldexp(1.0, exponent)
        angles.update((math.nextafter(value, 0.0), value, math.nextafter(value, math.inf)))
    angles.update(-value for value in list(angles))
    with localcontext() as context:
        context.prec = 460
        pi = compute_pi()
        # Also emit the independently derived fixed-point reducer constant for review.
        constant = int((2 / pi) * (1 << 1152))
        print("floor((2/pi)*2^1152), little-endian words:")
        print(", ".join(f"0x{(constant >> (32*i)) & 0xffffffff:08x}u" for i in range(36)))
        lines = ["// Generated by tests/quaternion_reference/generate_trigonometric_reference.py.",
                 "// 460-digit Decimal reduction and Taylor series; no native/libm oracle.",
                 "#pragma once", "namespace TrigonometricReference {",
                 "struct Sample { double angle, sine, cosine; };",
                 "static const Sample Samples[] = {"]
        for value in sorted(angles):
            sine, cosine = sincos(value, pi)
            lines.append(f"    {{{value:.16e}, {sine:.16e}, {cosine:.16e}}},")
        lines.extend(("};", "} // namespace TrigonometricReference", ""))
        (test_dir / "TrigonometricReferenceSamples.h").write_text("\n".join(lines))
        print(f"Generated {len(angles)} references")


if __name__ == "__main__":
    main()
